name: smartpay
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.2 <4.0.0"

workspace:
  - package/ui
  - package/pocketbase_sdk

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  turkmen_localization_support: ^0.0.11

  # UI
  cupertino_icons: ^1.0.8
  pinput: ^5.0.0
  mask_text_input_formatter: ^2.9.0
  collection: ^1.19.1
  async: ^2.12.0
  meta: ^1.16.0

  # Storing data
  shared_preferences: ^2.5.3

  # State
  control: ^0.2.0

  # Logging
  l: ^5.0.0
  stack_trace: ^1.12.1

  # Packages
  ui:
    path: package/ui
  pocketbase_sdk:
    path: package/pocketbase_sdk

  # Utils
  web: ^1.1.1
  path: ^1.9.1
  win32: ^5.12.0
  platform_info: ^5.0.0
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^5.0.0

  # Utils
  flutter_gen_runner: ^5.10.0
  pubspec_generator: ^4.2.2
  intl_utils: ^2.8.10
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/icons/
    - assets/images/
    - .env

flutter_gen:
  output: lib/src/common/constant/generated
  line_length: 120

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: ru
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false
