name: pocketbase_sdk
description: PocketBase SDK for Flutter
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

# https://dart.dev/tools/pub/workspaces
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.16.0
  pocketbase: ^0.22.0  
  shared_preferences: ^2.5.3

dev_dependencies:
  # Test
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  shaders:
    - packages/ui/shaders/shimmer.frag
